# ガジェットの名前は opTimelinePlugin v1.x と合わせる
# （管理画面からガジェットを追加し直さなくても表示できるようにするため）

smtTimeline:
  caption:
    ja_JP: "SNSメンバーのタイムライン"
  description:
    ja_JP: "SNSメンバー全員のタイムラインが表示されます"
  component: [timelineGadget, smtHomeAll]
